Feature/con 134/search modal universal query
oat-sa/tao-core-ui-fe pull request #219
Opened 2020-11-16 10:42 UTC by bartlomiejmarszal

Rename query param to pass to search endpoint

https://oat-sa.atlassian.net/browse/CON-134

2020-11-16 13:46 UTC, habemuscode requested changes
1- Bump version on `package.json` and run `npm install` and push `package.json` and `package-lock.json`
2- I see changes in `package-lock.json` related to that `adobe-webpatform`, maybe we need to discard that changes

2020-11-17 09:51 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2020-11-17 10:05 UTC, habemuscode approved these changes

2020-11-17 10:05 UTC, habemuscode commented
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2020-11-17 11:19 UTC, merged