Fix/aut 1667/wrap text img positioned outside a block
oat-sa/tao-core-ui-fe pull request #419
Opened 2022-01-20 15:46 UTC by Silvia-loza

Related to Related to 
 https://oat-sa.atlassian.net/browse/AUT-1667 
 https://github.com/oat-sa/extension-tao-itemqti/pull/2003

**Config** and **steps** to follow as explained [here:](https://github.com/oat-sa/extension-tao-itemqti/pull/2003)

**ACTUAL RESULT:**
in item authoring and shared stimulus authoring, image overflows outside the container when text wrap is used.
In New UI and Terre delivery view alignment is not correct.

**EXPECTED RESULT:**
item and shared stimuluss authroing image is within the container.
Items are viewed with alignement as authored in terre and solar delivery

2022-01-24 13:10 UTC, bziondik requested changes

2022-01-24 13:10 UTC, bziondik commented on scss/inc/_grid.scss
> +    &:before {
https://github.com/oat-sa/tao-core-ui-fe/blob/ab598265609cd90ee148c7bf2e2a0732e13e2ad3/scss/inc/_variables.scss#L13-L21
before and after already included in extend %clearfix

2022-01-25 10:00 UTC, clagosarias approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [ ]  The feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request's target is not master

2022-01-27 08:39 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2022-01-31 14:32 UTC, merged