feat: hide tabs container if none
oat-sa/tao-core-ui-fe pull request #460
Opened 2022-05-17 19:28 UTC by meefox

3/3
Related to https://oat-sa.atlassian.net/browse/AUT-1982

**Description:**
Hide tab holder if no tabs are provided and 'hideLoneTab' option set to true
Changes:
* Changed hide to main tabs holder container
How to check:
* Please see PR
Requires:
* Install PR
* Install PR

2022-05-19 10:51 UTC, jsconan requested changes
The idea of hiding the whole tabs bar when only one tab is present is legitimate. Especially since the tabs bar may have styling that won't behave well if no tab is displayed.

However, the approach is harmful with respect to its container.

2022-05-19 10:51 UTC, jsconan commented on src/tabs.js
> +            hider.hide(component.getElement().parent());
**issue:** This is harmful to the container. Except for very particular cases, a component must not try to modify its container. In this particular case, what will happen if the tabs are living aside from other components? All will be hidden for no reason.

**suggestion:** Please consider hiding the component itself. Do not forget to remove the unused resource import for `'ui/hider'` too.
```suggestion
            component.hide();
```

2022-05-19 11:46 UTC, shaveko approved these changes
Looks good, works well together with the related PRs

2022-05-19 12:09 UTC, jsconan approved these changes
**Review Checklist**
- [ ] ~~New code is covered by tests (if applicable)~~
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

2022-05-19 12:14 UTC, jsconan commented
@meefox BTW, you should also remove the unused import for `ui/hider`

<img width="859" alt="image" src="https://user-images.githubusercontent.com/1500098/169290747-88ff1539-4383-4552-b193-51afe84d531f.png">

2022-05-19 12:19 UTC, jsconan approved these changes

2022-06-01 07:54 UTC, AntonNeviarouski commented
QA verified

2022-06-01 09:28 UTC, merged